### ISSUE TITLE
Startpage is Glitched

### ISSUE THREAD

**Issue by AnguisCaptor** [xtr4nge/FruityWifi#100]
Well, just like the title says, I tried putting it now on a different system, so I simply ran the install-Fruitywifi.sh and the install went fine without errors
But when I look at the start page, image: http://puu.sh/guXpm/ae627518a8.png

Unable to login, what is that extra textbox doing at the top ?

**Comment by xtr4nge** [comment]
Hi AnguisCaptor,
I hope you are well.
FruityWifi uses short_open_tag. Please check PHP short_open_tag as in the screenshot looks like that is the problem.

regards,
xtr4nge
