### ISSUE TITLE
Starting up FruityWifi

### ISSUE THREAD

**Issue by joeyj2468** [xtr4nge/FruityWifi#101]
Hello,

I got wifi working and FruityWifi on raspberry pi.  However, everytime I shutdown and reboot I notice the ports are closed.  What command is used to start FruityWifi everytime on boot?  Also, I noticed the modules were not installed.  I saw a file in FruityWifi-Master (install-modules.py).  Would I just do ./install-modules.py like that?  Thanks.

**Comment by xtr4nge** [comment]
Hi joeyj2468,
I hope you are well.
Did you installed FruityWifi using the script `install-FruityWifi.sh`?

You can run the following commands for autostart:

`update-rc.d -f apache2 remove`
`update-rc.d nginx defaults`
`update-rc.d php5-fpm defaults`

About the modules, by default FruityWifi does not install any module. You can install all of them using `install-modules.py` or you can install each of them manually from Modules page on FruityWifi interface.

regards,
xtr4nge
