### ISSUE TITLE
No DHCP server with dnsmasq and hostapd

### ISSUE THREAD

**Issue by jmmalcala** [xtr4nge/FruityWifi#103]
All clients connected by WiFi with hostpad can´t obtain IP Address but with airmon-ng can acquire IP.

**Comment by xtr4nge** [comment]
Hi jmmalcala,
That is the behaviour of wireless cards not supported by Hostapd. 
Hostapd is what FruityWifi uses by default but Airmon-ng was provided as an alternative to support more wireless cards. 

Note: Karma and Mana can only be used with Hostapd modes.

regards,
xtr4nge
