### ISSUE TITLE
Unable to run Mana mode

### ISSUE THREAD

**Issue by jmmalcala** [xtr4nge/FruityWifi#104]
I have atheros black with chipset AR9271. It runs wiht hostapd mode but with mana mode no happens anything.

When i try to run manually start module command /usr/share/fruitywifi/www/modules/mana/includes/hostapd_cli karma_enable shows:

Failed to connect to hostapd - wpa_ctrl_open: No such file or directory

Thanks a lot.

**Comment by jmmalcala** [comment]
Solved

First config hostpad-mana then start wireless service and finally start Mana.

**Comment by xtr4nge** [comment]
Cool, thanks a lot for let me know that it was solved ;)

regards,
xtr4nge
