### ISSUE TITLE
Mana not install

### ISSUE THREAD

**Issue by lnkakalink** [xtr4nge/FruityWifi#107]
Mana is not installed put the new system updated set all modules and mana does not work as karma
Mana install from a Web interface is not installed
![93e1lfyp0y71zslufpzww 1](https://cloud.githubusercontent.com/assets/5696232/6855091/7e84ccce-d406-11e4-9b44-9a5b208e9974.jpg)
![phmzn0adfegteeiywldfjw 1](https://cloud.githubusercontent.com/assets/5696232/6855100/950828d8-d406-11e4-8bfd-5517ddd866b5.jpg)

**Comment by xtr4nge** [comment]
Hi lnkakalink,
run the installer from the console to debug the problem:
/usr/share/fruitywifi/www/modules/mana/includes/install.sh

regards,
xtr4nge
