### ISSUE TITLE
Can't open FruitWifi web interface. Using raspberry pi with Kali Arm image.

### ISSUE THREAD

**Issue by joeyj2468** [xtr4nge/FruityWifi#110]
Hello,

I am trying to open up my fruitywifi's web interface.  However, it states web page is unavailable.  Ports 8000 and 8443 are open as well.  Nginx and php5 are working and restarted.  Does anything need to be updated?  I saw 2.1 and was wondering if that came out a few days ago.  Let me know when you get a chance.  

Thanks,

-Joe

**Comment by xtr4nge** [comment]
Hi joeyj2468
- check that Apache it is not running
- restart nginx
- restart php5-fpm
- check that ports 8000 and 8443 are open

If ports 8000 and 8443 are not running and/or php is not working, you have a problem on Nginx and php5-fpm setup.

regards,
xtr4nge
