### ISSUE TITLE
Can't get nessus module to enable

### ISSUE THREAD

**Issue by joeyj2468** [xtr4nge/FruityWifi#112]
Hello,

I hope you are well.  I have been having issues with the modules, especally nessus.  When I try to start it, it still goes disabled.  Is something needed for nessus to work? if so, will that include the rest of the modules.  Nmap still gives me an error when I start it up.  Please advise.  Thank you.

![capture](https://cloud.githubusercontent.com/assets/11360105/7150001/b568dac4-e2e2-11e4-8328-a2828301478b.PNG)

**Comment by xtr4nge** [comment]
Hi joeyj2468, I hope you are well.
You need to download and install Nessus from tenable website first. FruityWifi Nessus module is only an interface to interact with Nessus.

You need to have nmap installed and it cannot be used from the status/wsdl page, you can only use it from the Nmap module page.

regards,
xtr4nge

**Comment by joeyj2468** [comment]
Ok.  Is there a nessus arm for raspberry pi? I have been trying to install it, but it appears there is no version.  I could be wrong and maybe looking in the wrong place.  Any leads to installing nessus on raspberry pi would be helpful.  Thanks.

**Comment by xtr4nge** [comment]
Hi joeyj2468,
There is no Nessus ARM version yet.
You can setup a remote server from Nessus module, or you can install FruityWifi on another architecture.

regards,
xtr4nge
