### ISSUE TITLE
path problem

### ISSUE THREAD

**Issue by SimoneRighitto** [xtr4nge/FruityWifi#116]
Inside the status_wireless.php file :
https://github.com/xtr4nge/FruityWifi/blob/master/FruityWifi/www/scripts/status_wireless.php

there are some broken path, for example line 126:

usr/share/fruitywificonf/hostapd.conf    I think this should be usr/share/fruitywifi/conf/hostapd.conf

let me know if I'm right and please fix this ;-)

**Comment by xtr4nge** [comment]
Hi SimoneRighitto,
I hope you are well, Thanks a lot for reporting this.

regards,
xtr4nge
