### ISSUE TITLE
Wrong port when saving module status

### ISSUE THREAD

**Issue by lillstrumpa** [xtr4nge/FruityWifi#118]
hi,

I have opend port 9000 in my router and points it to 8000 on my rpi at home..
my issues:

I can login and everything works fine from my cellphone, except when saving module status, from disabled. to enabled , then the script send me back to port 8000 and the session crashes , if i change the port back to 9000 agian I get the login screen and I can login, and the changes have been activated...

**Comment by xtr4nge** [comment]
Please re-open this thread in the forum if required: http://fruitywifi.boards.net/

regards,
