### ISSUE TITLE
isc-dhcp-server fail to start 

### ISSUE THREAD

**Issue by M4dMax** [xtr4nge/FruityWifi#120]
I did a apt-get install fruitywifi on a kali linux arm version using a raspberry pi model b with an aws036nh wireless card. i also modified /etc/network/interfaces to avoid conflict with fruitywifi,but it seems that isc-dhcp-server do not start. i tried manually but no luck. can you please help me

**Comment by xtr4nge** [comment]
Hi M4dMax,
FruityWifi uses dnsmasq as server.
Please search the issues history as some users reported problems with your
wireless card model.

Regards
xtr4nge

**Comment by M4dMax** [comment]
Many thanks
