### ISSUE TITLE
eth0 Interface disapper ? 

### ISSUE THREAD

**Issue by j0kara** [xtr4nge/FruityWifi#130]
Hi, today i started playing with furitywifi and it looks really amazing, but i'm having a few problems with it. My problem is that my eth0 interface is dissaper or get disabled, but i don't know how to get it back.

When i type 'ifconfig' i don't see it, but when i type 'iwconfig' i can see - 'eth0      no wireless extensions.'

Any idea or is there any command how to get my interface back, reboot don't help out :/

(I tried on Raspbian OS, on RPI and also on kali linux at regular laptop, issue happening at both machines)

**Comment by demogorgonz** [comment]
Try : 
ifup eth0
or
ifconfig eth0 up

Replace eth0 with your interface name...

**Comment by j0kara** [comment]
I already tried 'ifconfig eth0 up' and after that it shows up my eth0 interface but i have no internet. I also tried to reinstall Raspbian and then it work again but problem happend again after a hour or so.

**Comment by xtr4nge** [comment]
Please re-open this thread in the forum if required: http://fruitywifi.boards.net/

regards,
