### ISSUE TITLE
Modules not starting

### ISSUE THREAD

**Issue by MarquisT** [xtr4nge/FruityWifi#132]
I'm only able to get the wireless module to start. Any other module changes to enabled for a second, then changes to disabled. 

Any idea why modules won't start? I'm using a RPI and version 2.1.2
Is there an error log that will show me why these won't start?

**Comment by xtr4nge** [comment]
Hi MarquisT,
Please notice that some chipsets (like Realtek) are not supported by Hostapd. If this is the case, you need to switch the [AP] mode to Airmon-ng, but some modules like Karma and Mana will not work with this setup.

regards,
xtr4nge

**Comment by xtr4nge** [comment]
Please re-open this thread in the forum if required: http://fruitywifi.boards.net/

regards,
