### ISSUE TITLE
Cannot see any module in the list

### ISSUE THREAD

**Issue by adrianTNT** [xtr4nge/FruityWifi#139]
I am using Raspberry PI and I installed it with the .sh script downloaded.
At first start of FruityWifi, I open the modules page, one of the methods listed the modules, then I restarted the raspberry because it would not recognize my wlan dongle (no wlan interface), I put another one in and restarted, this one is able to start the wlan interface OK, but no modules show on the modules page. 
I am not sure if is related to changing he wlan dongle or not, maybe just the reboot alone caused this.
Edit: the "reveal ip" next to "public" shows blank, it used to show my public IP.

**Comment by xtr4nge** [comment]
Hi adrianTNT,
you can see the following message on the modules page:

`List available modules [tar.gz]`
`This will establish a connection to github.com/xtr4nge`

Press on `List available modules [tar.gz]` and you will see the list of all available modules that you can install (internet connection required)

Let me know 
regards,
