### ISSUE TITLE
Cannot connect to localhost

### ISSUE THREAD

**Issue by lotiebrink** [xtr4nge/FruityWifi#150]
Hi,

I installed FruityWifi on my SIFT Workstation 3.0, but now I cannot open the UI as I cannot connect to the http or https localhost.  The one gives me "Bad Gateway" and the other one gives me Untrusted Connection. The Untrusted Connection is because I signed the certificate myself.  How can I rectify the problem?

**Comment by xtr4nge** [comment]
Hi lotiebrink,
restart/start `nginx` and `php5-fpm`, then hit the ports 8000 (HTTP) or 8443 (HTTPS)

Let me know
regards,

**Comment by xtr4nge** [comment]
Please re-open this thread in the forum if required: http://fruitywifi.boards.net/

regards,
