### ISSUE TITLE
how to use MITMf?

### ISSUE THREAD

**Issue by twayz** [xtr4nge/FruityWifi#152]
Hi,

Thank you so much for adding so many different modules. I am not able to get the sslstrip2 module to work correctly whether I enable it from within MITMf or by itself. It correctly redirects https:// domains. However, the page it redirects it to is always unavailable. But, when I manually run mitmf.py from the modules folder without starting FruityWifi, it correctly redirects https:// domains. I was wondering if maybe I am doing something wrong? I usually use these options when I run MITMf.py manually:

./mitmf.py -i eth0 --spoof --arp --hsts --gateway 192.168.11.1 --target 192.168.11.xx --log debug

and it works. I also have the hsts plugin enabled from the fruitywifi admin page. Is there anything specific I have to do in order to get MITMf working from fruitywifi admin page?

Thank you so much!
Twayz

**Comment by xtr4nge** [comment]
Hi twayz,
`MITMf` core is SSLstrip2 so you don't need to start `sslstrip2` module, just start MITMf.

regards,

**Comment by xtr4nge** [comment]
Please reopen the topic in the forum if required: http://fruitywifi.boards.net/

regards,
