### ISSUE TITLE
Can't find the FruityWifi network

### ISSUE THREAD

**Issue by DiegoCaridei** [xtr4nge/FruityWifi#154]
Hi, i installed FruityWifi 2.2 on Kali Linux 2.0 and i am able to enable AP and Karma services.
![schermata 2015-08-29 alle 23 30 20](https://cloud.githubusercontent.com/assets/1045744/9564383/f0a80694-4ea5-11e5-9b12-c7bcdf9a4bfa.png)
Now... on my mobile phone i can't see an then connect to FruityWifi network to test some modules like DNSspoof
![schermata 2015-08-29 alle 23 29 54](https://cloud.githubusercontent.com/assets/1045744/9564388/2f56dbc2-4ea6-11e5-8a36-001acf3066ff.png)
How can i solve this situation?

**Comment by xtr4nge** [comment]
Hi DiegoCaridei ,
Your setup is incorrect. You need to specify the details for the AP that FruityWiFi is going to create (based on your screenshot, I see that you are using wlan2) 
Change the config of IN [wlan2] to manual and define the details.

To continue with this topic, please open a post in the forum. http://fruitywifi.boards.net/

regards,
