### ISSUE TITLE
Nmap error while installing modules

### ISSUE THREAD

**Issue by AnguisCaptor** [xtr4nge/FruityWifi#155]
On the Raspberry PI 2 I noticed when using the install-modules.py it will give the following error for nmap

nmap v1.4
git clone https://github.com/xtr4nge/module_nmap.git /usr/share/fruitywifi/www/modules/nmap
Cloning into '/usr/share/fruitywifi/www/modules/nmap'...
remote: Counting objects: 48, done.
remote: Total 48 (delta 0), reused 0 (delta 0), pack-reused 48
Unpacking objects: 100% (48/48), done.
chmod: cannot access `install.sh': No such file or directory
sh: 1: /install.sh: not found

**Comment by xtr4nge** [comment]
install.sh has been added.

regards,
