### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by sampsonc** [xtr4nge/FruityWifi#156]
Getting a "502 Bad Gateway" error when navigating to http://localhost:8000 and https://localhost:8443.

**Comment by xtr4nge** [comment]
Hi sampsonc,
You need to start Nginx and php5-fpm services.

regards,

**Comment by Tamanbir** [comment]
Could you please give a proper latest step to install fruitywifi on nethunter(latest version)
I am having a lot of problem, nginx don't work, sometimes php7 directory is not found. So it would be bettter if ypu provide a proper steps to install fruitywifi on nethunter, althought nethunter has bydefautl service to switch on fruitywifi but it doesn't work.
