### ISSUE TITLE
Help Me 

### ISSUE THREAD

**Issue by vinod3070** [xtr4nge/FruityWifi#157]
None of the modules  are working for me ??  helps me out 
![screenshot 1](https://cloud.githubusercontent.com/assets/13526641/9630266/b852f36e-5196-11e5-88b4-eb8bf6a51b1b.png)
are working for me ??

**Comment by xtr4nge** [comment]
Hi vinod3070,
Please open a thread on the forum:
http://fruitywifi.boards.net/

Regards
