### ISSUE TITLE
logs display modules / plugins that are not running.

### ISSUE THREAD

**Issue by vsboost** [xtr4nge/FruityWifi#163]
noticed that under the logs screen that it displays logs of modules that are not running, for example when i was playing around with getting karma running the logs for karma showed up but after i stopped that module from running and after many reboots the logs still show up in that tab, not sure if that's by design.

**Comment by xtr4nge** [comment]
Hi vsboost,
Originally it was, but lately (on new modules and updates) I started moving the log to History, as soon as the module is stopped.

regards,
