### ISSUE TITLE
DHCP Don´t Work

### ISSUE THREAD

**Issue by qdiegoq** [xtr4nge/FruityWifi#164]
Im using : 
TP-Link TL-WN722N

When i use "Hostapd" 

I start the [ap] Service nothing happens.it start and stop.

When i use "airmon-ng" the Access point its generated but not DHCP.

The Clients can´t get an ip.

Can you help me?

**Comment by xtr4nge** [comment]
Hi qdiegoq,
Check this thread in the forum for debugging:
http://fruitywifi.boards.net/thread/65/rpi-kali-01-fruitywifi-issues

regards,
