### ISSUE TITLE
wlan0mon not detected

### ISSUE THREAD

**Issue by grayburn** [xtr4nge/FruityWifi#166]
Running Fruitywifi 2.2 on a Raspberry Pi 2 with Kali 2.0. Latest version of aircrack-ng does not use mon0 anymore. Under config >> additional interfaces, I select my wlan0 device (TP-Link WN722N) and click start. On the terminal, iwconfig shows my wlan0mon device but FruityWifi does not show it. I am assuming it is expecting mon0.

**Comment by xtr4nge** [comment]
Hi grayburn,
Thanks for the info, I will take a look ;)

regards,

**Comment by chilcano** [comment]
Hi there, 
I am facing the same problem. I have fixed by modifying `/usr/share/fruitywifi/www/functions.php` as follow:

```bash
...
function start_monitor_mode($iface) {

    $bin_danger = "/usr/share/fruitywifi/bin/danger";

    // START MONITOR MODE (mon0)
    $iface_mon0 = exec("/sbin/ifconfig |grep mon0");
    if ($iface_mon0 == "") {
        ////$exec = "/usr/bin/sudo /usr/sbin/airmon-ng start $iface";
        //exec("$bin_danger \"" . $exec . "\"", $output); //DEPRECATED
        ////exec_fruitywifi($exec);

        // ****
        $exec = "/usr/bin/sudo iw phy phy0 interface add mon0 type monitor";
        exec_fruitywifi($exec);
        $exec = "/usr/bin/sudo iw dev wlan0 del";
        exec_fruitywifi($exec);
        $exec = "/usr/bin/sudo /sbin/ifconfig mon0 down";
        exec_fruitywifi($exec);
        $exec = "/usr/bin/sudo /sbin/iwconfig mon0 mode monitor";
        exec_fruitywifi($exec);
        $exec = "/usr/bin/sudo /sbin/ifconfig mon0 up";
        exec_fruitywifi($exec);

     }

}

function stop_monitor_mode($iface) {

    $bin_danger = "/usr/share/fruitywifi/bin/danger";

    // START MONITOR MODE (mon0)
    $iface_mon0 = exec("/sbin/ifconfig |grep mon0");
    if ($iface_mon0 != "") {
        ////$exec = "/usr/bin/sudo /usr/sbin/airmon-ng stop mon0";
        //exec("$bin_danger \"" . $exec . "\"", $output); //DEPRECATED
        ////exec_fruitywifi($exec);

        // ****
        $exec = "/usr/bin/sudo iw dev mon0 del";
        exec_fruitywifi($exec);
        $exec = "/usr/bin/sudo iw phy phy0 interface add wlan0 type managed";
        exec_fruitywifi($exec);
        $exec = "/usr/bin/sudo /sbin/ifconfig wlan0 up";
        exec_fruitywifi($exec);

    }

}
...
```

Regards.

**Comment by c0mix** [comment]
i had the same problem, just search mon0 in this repo, open the interested files and change "...grep mon0..." with "... grep 'mon0 | wlan0mon'"

**Comment by chilcano** [comment]
Nice trick c0mix !

In my case (exopc + kali linux) `airmon-ng start wlan0` doesn't work for 2 reasons:
* `lsusb` isn't installed
  * `$ sudo apt-get install usbutils`
* `airmon-ng` creates `wlan0mon` instead of `mon0`

regards.

**Comment by xtr4nge** [comment]
Hi guys,
Fixed on FruityWiFi v2.3 without using airmon-ng. I will keep the monitor interface as mon0 for the time being.

regards,

**Comment by nadirchine** [comment]
@Chicano ! I have the same problem with airmon-ng ... There is only wlan0mon

**Comment by xtr4nge** [comment]
Hi nadirchine,
You need to upgrade to FruityWiFi v2.3 to fix the problem on `Additional Interfaces` 
(mon0 vs wlan0mon issue)

regards,

**Comment by nadirchine** [comment]
thankyou very much, i  will upgrade it

Sent from Outlook Mobile




On Mon, Feb 1, 2016 at 12:03 PM -0800, "xtr4nge" <notifications@github.com> wrote:





Hi nadirchine,
You need to upgrade to FruityWiFi v2.3 to fix the problem on `Additional Interfaces`
(mon0 vs wlan0mon issue)

regards,

---

**Comment by whywant** [comment]
Looking for my friend：Medjitena Nadir，Who has his email address? Please tell me，Thanks
