### ISSUE TITLE
Karma Module in Fruitywifi v2.2 dont start

### ISSUE THREAD

**Issue by Donluigimx** [xtr4nge/FruityWifi#168]
I can't get the karma module work. I also have tried with mana module. The Access Point works fine. Im using TL-WN722N adapter in a rpiB+ with kali and in a PC with Ubuntu 14.4. (Sorry for my bad english)

**Comment by xtr4nge** [comment]
Hi Donluigimx,
This is a topic for the forum. There is a lot info related there, and you can start checking here:
http://fruitywifi.boards.net/thread/52/faq
http://fruitywifi.boards.net/thread/59/suported-wlan-adapter

If you can't solve the problem, please open a new thread in the forum for help.

regards,
