### ISSUE TITLE
Cannot install any uninstalled external modules

### ISSUE THREAD

**Issue by gh0stshell** [xtr4nge/FruityWifi#169]
it shows downloading then nothing

**Comment by gh0stshell** [comment]
2015/10/30 01:12:24 [error] 594#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught exception 'Requests_Exception' with message 'cURL error 7: Failed to connect to 127.0.0.1 port 8081: Connection refused' in /usr/share/fruitywifi/www/modules/fruityproxy/includes/Requests/Requests/Transport/cURL.php:291

**Comment by gh0stshell** [comment]
I can use curl from the CLI and connect to 8081

**Comment by gh0stshell** [comment]
I am using a R Pi running Kali arm and installed FruityWifi via apt-get

**Comment by gh0stshell** [comment]
I am running version 2.2 and trying any of the modules that have install listed next to them such as tor or stalker

**Comment by xtr4nge** [comment]
Hi gh0stshell,
It looks like you have a problem with the core installation/setup.
This is a topic for the forum. Please open a new thread in:
http://fruitywifi.boards.net/

regards,
