### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by gh0stshell** [xtr4nge/FruityWifi#170]
If using a Rasp Pi running Kali Arm latest, can I use the repo install method or am I suppose to be using the install script method? I wonder if this is why I cannot install any non installed modules.

**Comment by gh0stshell** [comment]
I am getting no responses on that board you send me to.

**Comment by gh0stshell** [comment]
i can install using the apt-get option, but not the tar.gz option

**Comment by gh0stshell** [comment]
if install using the scripts I can install all the modules, if i use the kali repo I cannot install modules that are not in the repo. I also cannot issue fruitywifi-module-name per your wiki.

**Comment by gh0stshell** [comment]
using the scripts I also get no proxy errors in my logs, where can I see what is happening when I try installing a module using the tar.gz method? I think the log data is not showing the errors when trying to install using the tar.gz option.

**Comment by gh0stshell** [comment]
able to install plugins under fruityproxy>plugins without any issues

**Comment by gh0stshell** [comment]
I cannot use "Try to run the installation script manually. Each module|plugin contains an installation script. Go to the folder /usr/share/fruitywifi/www/modules/{module-name}/includes/ and execute manually the script install.sh." since I installed from the kali repo

**Comment by xtr4nge** [comment]
Please go to the forum, this is not a topic for GitHub.

regards,
