### ISSUE TITLE
admin admin not working

### ISSUE THREAD

**Issue by wermaxta** [xtr4nge/FruityWifi#174]
Hi is have problem with fruitywifi admin password on kali linux 2.0 
password not working how i can change it
I start /etc/init.d/fruitywifi start then /etc/init.d/php5-fpm start and i'm going on my iceweasel end i type
http://localhost:8000 i see FruityWifi login page and when i type user admin pass admin nothing happen
my OS  Linux kali 4.0.0-kali1-686-pae #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) i686 GNU/Linux
Thank you :))

**Comment by xtr4nge** [comment]
Hi wermaxta,
If you didn't change the password, then should be user: `admin` and pass: `admin`
A few checks to do: http://fruitywifi.boards.net/thread/52/faq

Do you have space in the disk?

Please take a look on the forum and open a new thread if required: http://fruitywifi.boards.net

regards,
