### ISSUE TITLE
504 Gateway Time-out  nginx/1.2.1

### ISSUE THREAD

**Issue by Ramses2056** [xtr4nge/FruityWifi#176]
Hi, im having a strange issue after the installation of fruitywifi on Rpi model B. Im using Pwnpi-3.0 on my SD card. I installed fruitywifi  and its modules via the master.zip file(./install-Fruitywifi.sh && ./install-modules.py). after the very long installation i tried to start my AP module on fruitywifi and it give me this error {504 Gateway Time-out nginx/1.2.1}. i had check all services with {service --status-all} and everything seems to be ok. Unfortunately the last part freaked me out. As soon as i did a reboot on my Pwnpi3.0 i cant even ssh back to my pi. It says that the host is down . can you please help me get   that cool software up and running?

**Comment by xtr4nge** [comment]
Hi Ramses2056,
You need to start/restart nginx and php5-fpm
Also check that you have space on the SD card.

regards,
