### ISSUE TITLE
There are same problem in other modules

### ISSUE THREAD

**Issue by darkr4y** [xtr4nge/FruityWifi#180]
I have reported a bug two days ago,
there are same problem in other modues's code.
plz review it , eg: get the interface function.

**Comment by xtr4nge** [comment]
Hi darkr4y,
I know about the modules that need to be updated, and I will publish the new versions as soon as I can.
I fixed the main issue that it was the core and the AP module.
It was a compatibility issue because of changes in Kali Linux Rolling.

regards,
