### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by wikijm** [xtr4nge/FruityWifi#183]
How to uninstall FruityWifi and modules?

**Comment by xtr4nge** [comment]
There is not uninstaller unless that you installed it from Kali Linux repository and not from GitHub. FruityWiFi is not a package that you can remove all together as it is mainly a wrapper to interact with other software. 
The main container for FruityWiFi is in `/usr/share/fruitywifi`, but removing this folder will not remove the dependencies or the system setup (sudo, nginx, php).
Each module installs dependencies and each of these dependencies need to be removed manually.

**Comment by synaption** [comment]
Is there an easy way to turn it off?
