### ISSUE TITLE
AP/Karma not working??

### ISSUE THREAD

**Issue by FinlayDaG33k** [xtr4nge/FruityWifi#186]
When I try to setup an AP using FruityWiFi, 
it says that [AP] is enabled, but when I go to my laptop and check it, the AP is not listed.
I have no clue how the options should be as the documentation is quite outdated and bare (webUI say IN-OUT instead of Internet-Wifi for example)

my config at the moment is this:

- MODE: IN - --- [AP]
- [AP]: Hostapd-Karma
- IN:
  - Interface: wlan2
  - [Manual]
  - IP: 192.168.101.1
  - Netmask: 255.255.255.0
  - Gateway: empty
- stop [on]

**Comment by xtr4nge** [comment]
Hi FinlayDaG33k,
Your wireless card needs to be supported by Hostapd. Please go to the forum for more details and 

Forum: http://fruitywifi.boards.net
FAQ: http://fruitywifi.boards.net/thread/52/faq
Supported adapters (Hostapd): http://fruitywifi.boards.net/thread/59/suported-wlan-adapter

regards,

**Comment by FinlayDaG33k** [comment]
I found the issue that caused it: 
I had selected my onboard WiFi (an unsupported adapter) instead of my USB adapter (which is supported)

**Comment by FinlayDaG33k** [comment]
Unfortunately it didn't get solved.

I now have setup my `TL-WN722N` with FruityWifi, but the AP still doesn't show up anywhere (my tablet, my PC, my cellphone).

I'm using Kali2

**Comment by xtr4nge** [comment]
Check all the links and recommendations on the mentioned post.
I want to keep GitHub just for bugs, and this is a setup issue.

Search on the forum or post a new thread if required (on the forum).

regards,

**Comment by FinlayDaG33k** [comment]
After doing some tinkering, I managed to get the AP to work.
for somekind of unknown reason, the AP said it was on, but infact, it wasn't.

**Comment by xtr4nge** [comment]
Good, as I mentioned on the other issue, there are some services that can cause troubles, dnsmasq, network-manager, setup on interfaces, etc.

For further questions, please go to the forum ;)

regards,
