### ISSUE TITLE
TP-Link WN722N + Raspberry not working

### ISSUE THREAD

**Issue by d4rksou1** [xtr4nge/FruityWifi#187]
Hi,
I've tried install raspbian, kali and pwnpi and i can't make this work... I cannot start hostapd and it's suposed to be a compatible card ( AR9271 ). can this be a raspberry incompatibility? can it be a power issue? anyone else have this problem?

I'll wait for some feedback

THanks =)

**Comment by xtr4nge** [comment]
Hi d4rksou1, I hope you are well.
This is not a bug, it is just a setup issue, please post the question in the forum ;)
http://fruitywifi.boards.net

check supported wireless adapters threads and other threads related with RPi
http://fruitywifi.boards.net/thread/59/suported-wlan-adapter

check the FAQ:
http://fruitywifi.boards.net/thread/52/faq

Without a powered USB hub, AR9271 maybe will give you some problems on RPi

You need to check a couple of things:
- check that dnsmasq is not running
- remove all entries of the wireless cards that you are going to use with FruityWiFi from /etc/network/interfaces (wlan0, wlan1, etc.)
- check that network-manager is not running.

regards,
