### ISSUE TITLE
php_modules.php?show not showing any modules

### ISSUE THREAD

**Issue by Bry-fi** [xtr4nge/FruityWifi#190]
I have installed fruitywifi 2.4 with no modules and i try to list the modules and nothing loads on the page.
Also the AP refuses to start even though I have installed the core modules

**Comment by simonpunk** [comment]
Same situation here, I have followed the latest instruction to install the fruitywifi 2.4 and its all modules, but at the panel it still showing me no modules are installed. Don't know what happened.

**Comment by xtr4nge** [comment]
Hi guys, this is not a bug.
Please go to the forum and open a new thread (I need more info). I will help you there.
(What device, What os version, Debian, Kali, How did you installed FruityWiFi, etc...)

simonpunk, you need to be sure that the setup for the user fruitywifi is correct, please check this thread:
http://fruitywifi.boards.net/thread/111/fruitywifi-v2-4

Note: If you are on Kali Rolling, you just need to use **apt-get install**

regards,
