### ISSUE TITLE
fruity wifi won't start on linux mint

### ISSUE THREAD

**Issue by cmac7774** [xtr4nge/FruityWifi#195]
I've followed the installation instructions and am unable to start fruitywifi in a chrome or firefox window. It tells me this site cant be reached. I scoured google for answers and haven't found a way of getting up and running. Any help would be much appreciated.

**Comment by xtr4nge** [comment]
Hi cmac7774,
I never tried FruityWiFi on linux mint, but it should work on any Debian based system.

You can check a couple of things:
- Verify that /usr/share/fruitywifi/ exists.
- Verify that port 8000 and 8443 are open.
- Verify that php5-fpm is running.

Please go to the forum for more details and support. http://fruitywifi.boards.net
regards,
