### ISSUE TITLE
Fake AP

### ISSUE THREAD

**Issue by DarrenRainey** [xtr4nge/FruityWifi#202]
Hello  its been a while since I've used fruitywifi and I was wondering if it can pretend to be a known network like the wifi pineapple. basicly I want my access point to pretend to be the victims home network for example and have them automatically connect like with the wifi pineapple

**Comment by xtr4nge** [comment]
You can do that and more things without any problem. Go to the forum for more information. http://fruitywifi.boards.net

regards,
