### ISSUE TITLE
FruityWiFi on OpenWRT?

### ISSUE THREAD

**Issue by MatthewHKnight** [xtr4nge/FruityWifi#203]
Was just curious I thought FruityWiFi worked with OpenWRT does it not ? Cause I was looking for a guide on it but didn't look to hard but was curious if it could be installed on something like a Alfa Networks AP-121u

**Comment by xtr4nge** [comment]
Hi MatthewHKnight,
I never tried to port FruityWiFi to OpenWRT. FruityWiFi was created to be installed on any Debian based system. The majority of the dependencies are installed from the repository (apt-get) and using pip.
It can be ported to OpenWRT, but you will have a lot of work with the dependencies. Each module requires it owns dependencies, so every time that a new module is released, you will need to port the installer (dependencies).
There are are projects like DebianWRT and DebWRT (I never tried them yet), that could be an alternative to install FruityWiFi on wireless routers.

regards,
