### ISSUE TITLE
DHCP-DNS page not saving settings

### ISSUE THREAD

**Issue by FinlayDaG33k** [xtr4nge/FruityWifi#205]
When I go to my DHCP-DNS page (`/modules/ap/`) the settings I fill in, don't save at all

**Comment by xtr4nge** [comment]
Hi FinlayDaG33k,
This could be a permissions problem. FruityWiFi execs several commands using sudo (user fruitywifi).
You need to: 
- check that Nginx is running as fruitywifi user 
- check sudo setup for fruitywifi user.
- check folder and files permissions (/usr/share/fruitywifi/modules/ap/)

What hardware and OS are you using?
How did you install FruityWiFi? 

The installation script is doing all the permissions setup for you, and of course the same if you are using Kali Linux repo (apt-get...)

regards,

**Comment by FinlayDaG33k** [comment]
I think it's running as fruitywifi (`top -U fruitywifi` shows a few nginx processes)

I'm running on `Raspbian Jessie`.
when running `ls -l /usr/share/fruityiwifi/modules/ap/` I get `No such file or directory`.
However, when I do `ls -l /usr/share/fruityiwifi/www/modules/ap/` I see it's owned by `root`.

Upon trying more stuff from the FruityWifi suite, I noticed that the DNSspoof also doesn't work.

I've tried FruityWifi on my laptop (with ParrotOS) with great success, so I think it's the combination of Pi and Fruitywifi that goes wrong...

**Comment by FinlayDaG33k** [comment]
Oh yea, I installed FruityWifi with the [installer script](https://github.com/xtr4nge/FruityWifi/blob/master/install-FruityWiFi-PHP7.sh)

**Comment by FinlayDaG33k** [comment]
After doing a little test, I confirmed that it's most likely a configuration issue.
when running the AP module with only IN, no OUT, I can still ping the internet trough the AP.

**Comment by xtr4nge** [comment]
If you are using Raspbian, you need to use **install-FruityWiFi.sh** and not install-FruityWiFi-PHP7.sh
I created install-FruityWiFi-PHP7.sh version for Kali Linux as they remove php5 from the repo.

Note: yes the correct path is: /usr/share/fruitywifi/www/modules/ap/
regards,

**Comment by FinlayDaG33k** [comment]
ah okay :) I will reinstall Fruitywifi with the other one instead :) will report back to you

**Comment by xtr4nge** [comment]
Cool, yes, let me know ;)
Thanks

**Comment by FinlayDaG33k** [comment]
Reinstalled it with `sudo ./install-FruityWiFi.sh` , still the same issue :\ 
Here is a screenshot of my config:
![image](https://cloud.githubusercontent.com/assets/13424273/19066021/5d2301b8-8a17-11e6-979e-b02943009b49.png)

And again, when I try to ping a server, with this config, FruityWifi still let's traffic trough to the interwebs.

**Comment by FinlayDaG33k** [comment]
Changing the config to the following made me able to "block" all traffic to the internet:
![image](https://cloud.githubusercontent.com/assets/13424273/19066620/6949b51a-8a1a-11e6-9874-9c9f4e440a7c.png)

Still trying to figure out why the DNSSpoof plugin doesn't spoof anything at all...

**Comment by xtr4nge** [comment]
Hi FinlayDaG33k,
But I see that you can save the settings. It was not that your problem?

About DNSspoof, that module has been deprecated. You need to use FruityDNS module for DNS spoofing.

The functionality for MODE has not been implemented yet. The change on the MODE (IN-OUT, IN-NONE, etc) doesn't have any impact (at the moment) in the setup. For now, the setup always uses IN Interface and OUT interface doesn't matter the MODE that you are assigning.

Please for more questions about the setup go to the forum ;)
http://fruitywifi.boards.net

regards,
