### ISSUE TITLE
3rd interface mon0 ? 

### ISSUE THREAD

**Issue by hadiabounader** [xtr4nge/FruityWifi#211]
Dear, 

I'm having issues setting up the interfaces.. 
if IN is for AP interface (wlan1 in my case) and OUT for the internet interface.. ( wlan0) in my case)

what's the interface for mon0 ? 
everytime i set it up to wlan1 or wlan0 it disconnects me from the network , help!

**Comment by xtr4nge** [comment]
Hi hadiabounader,
You need to setup and start **Monitor Interface** in MENU/Config, is below IN and OUT config

regards,

**Comment by hadiabounader** [comment]
I Mean Mon0 should be equal to the Access point (Wlan1) ?

**Comment by xtr4nge** [comment]
No, mon0 need to be a 3rd interface, it is not related with the interface **IN** being used for the Access Point.
The interface (Monitor Interface section) mon0 is used by some modules such as WiFiRecon, DetectDeauth, DetectRogue, MDK3, Kismet, and other modules that requires an interface in monitor mode.

regards,

**Comment by hadiabounader** [comment]
in my setup i have my raspberry built in wifi connected to the router ( internet), Ralink 5370 ( AP ) 
where am i supposed to put mon0 ?

**Comment by xtr4nge** [comment]
FruityWiFi creates mon0 when you enable "Monitor Interface" (3rd interface, setup below IN|OUT)
In your case wlan0 is OUT, wlan1 is IN.
If you don't have a 3rd interface to use modules that requires Monitor Mode, then you don't need mon0

regards,

**Comment by hadiabounader** [comment]
I need to use FruityDNS + Bettercap do i need mon0 ?

**Comment by xtr4nge** [comment]
No, you don't need mon0 for these 2 modules.
If you are having trobles with FruityDNS and Bettercap is because of missing dependencies. 
Go to the forum http://fruitywifi.boards.net/

regards,
