### ISSUE TITLE
Most modules can't be activated.

### ISSUE THREAD

**Issue by hadiabounader** [xtr4nge/FruityWifi#212]
Dear, 

Most of the Modules can't be activated such as : FruityDNS , BEeF , MIMTf etc.. how can i fix that 

Regards, 
Hadi :)

**Comment by xtr4nge** [comment]
Hi hadiabounader,
you need to verify that all the dependencies are installed. Please go to the forum as you will find a lot of information related with this. There is a section Modules, where each module is discussed.
Forum: http://fruitywifi.boards.net/

regards,
