### ISSUE TITLE
bdf install script infinite loop due to missing git

### ISSUE THREAD

**Issue by KALRONG** [xtr4nge/FruityWifi#214]
When I tried to install bdf in a fresh fruitywifi install on a lite jessie I found that it just kept looping and executing the script install.sh again and again, after trying to do it manuallly I found that I was missing git what caused the script to jump to the line where it calls himself again, after installing git it seems everything is working.

**Comment by xtr4nge** [comment]
Hi KALRONG,
Thanks, I will add git to the dependencies list.

regards,
