### ISSUE TITLE
Start ap issue 

### ISSUE THREAD

**Issue by arshiay** [xtr4nge/FruityWifi#217]
Hi
Thanks for script 
I have an issue 
I install this on kali on raspberry pi 3 and after boot and start php and fruitywifi AP shows in wifi menu in other devices but cant connect to
So i have to stop and star AP through browser 
My raspberry does have screen so i need AP to connect to it to control it
Is there any command to stop and start AP with terminal (i can put it in script to run at boot)
Or any solution?

**Comment by xtr4nge** [comment]
Hi arshiay,
You can use Automaton (http://fruitywifi.boards.net/thread/133/module-automaton) module or FruityShell (http://fruitywifi.boards.net/board/8/fruityshell).
Automaton uses the FruityWiFi API to start/stop modules or to execute any other command or module.
Please go to the forum: http://fruitywifi.boards.net/

**Comment by arshiay** [comment]
Thanks for reply 
I set new template in automation 
And set ssid 
Set protected to 1
And have a question how set my password ?

**Comment by xtr4nge** [comment]
For a secure AP you need to add the following to the Automaton template:
`SET /config/core/hostapd_secure/1`
`SET /config/core/hostapd_ssid/AP_NAME_HERE`
`SET /config/core/hostapd_wpa_passphrase/PASSPHRASE_HERE`

regards,
