### ISSUE TITLE
cannot start fruitydns

### ISSUE THREAD

**Issue by jeretc** [xtr4nge/FruityWifi#223]
hi for fake AP and fake portal page, what are the proper modules needs to be installed and started?
I can start the [AP] , but cannot start the fruityDNS. I can start the phishing page. AP is showing but external device cannot connect to fake AP .

**Comment by DanielL99** [comment]
Same here

**Comment by xtr4nge** [comment]
Hi guys, Captive Portal (same Phishing) module requires a few modules enabled (before starting Captive):

- AP
- FruityDNS (selected on AP as DNS server => DHCP-DNS tab => DNS)
- Nginx

About your problem with devices connecting to AP, be sure that the AP is working find and that the Wireless card is compatible, before starting more modules.
http://fruitywifi.boards.net/thread/59/suported-wlan-adapter

FruityDNS needs to be set as the DNS server on AP module before starting AP module.
All the dependencies for FuityDNS needs to be installed. When you accesss FruityDNS module, you can see the install/installed option. You can also reinstall all the dependencies manually: 
/usr/share/fruitywifi/www/modules/fruitydns/includes => install.sh

regards,
