### ISSUE TITLE
Imposible start nginx

### ISSUE THREAD

**Issue by tXambe** [xtr4nge/FruityWifi#224]
Hello,

When I start nginx falied and in the log appears:

[emerg] 7939#7939: bind() to [::]:80 failed (98: Address already in use)
[emerg] 7939#7939: still could not bind()

I don't know where looking for and what other service is configured in port 80.

Thanks and a greeting

**Comment by xtr4nge** [comment]
Hi tXambe,
You have have something running on port 80 or there is a problem on the Nginx config.

try: 
`netstat -tulnp |grep ":80"`

Try to stop the service nicely, or you can use `tcpkill` to force killing a connection.
But again, check that that your setup for NGINX+FPM is correct with the correct config files (PHP5|PHP7)

regards,
