### ISSUE TITLE
Captive starts, but doesn't work when device connects

### ISSUE THREAD

**Issue by dwagner5** [xtr4nge/FruityWifi#228]
I just get the "cannot find server" type error when I try to navigate to a webpage when connected to FruityWiFi.

**Comment by givemetatula** [comment]
Yeah, same for me. Please answer

**Comment by Supersqualo** [comment]
You must type https://localhost:8443

**Comment by xtr4nge** [comment]
Hi guys, Captive Portal module requires a few modules enabled (before starting Captive):
- AP
- FruityDNS (selected on AP as DNS server => DHCP-DNS tab => DNS)
- Nginx

regards,

**Comment by jeretc** [comment]
@xtr4nge i cannot start fruityDNS, i am using th github version, downloaded and installed using the script file. i can start all other module except fruitydns.
