### ISSUE TITLE
Short tags cause issues with autostart

### ISSUE THREAD

**Issue by alset333** [xtr4nge/FruityWifi#230]
Running Raspbian Jessie Lite, Version "July 2017".

The autostart module prints the PHP code to the screen, instead of running it.
I was able to easily fix this on my device by editing the PHP files and changing the short starting tag ( <? ) with the full PHP tag ( <?php ).

The relevant files I changed were located at:
/usr/share/fruitywifi/www/modules/autostart/includes/FruityWifi-autostart.php
/usr/share/fruitywifi/www/modules/autostart/includes/options_config.php

Simply changing the first line on each fixed the problem.

Hopefully the appropriate pieces of code can be changed here at the source, and possibly any other files that may have similar issues could be fixed as well.
In general short tags seem to be a common compatibility issue for otherwise well-written php.

**Comment by xtr4nge** [comment]
Hi alset333,
short_open_tag needs to be enabled for FruityWiFi
http://fruitywifi.boards.net/thread/52/faq

Autostart has been deprecated and replaced by **Automaton** module.

regards,
