### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by RechtDev** [xtr4nge/FruityWifi#233]
Hi. I keep getting 502 Bad Gateway error every time i open the link:localhost. I've used the apt get method to download FruityWifi and I used this command /etc/init.d/fruitywifi start and  /etc/init.d/php7.0-fpm start with both saying started. I dont know what to do.

**Comment by xtr4nge** [comment]
Hi RechtDev,
I hope you are well.
I know this message is very old, but FYI, I updated the installer to support systems based on Debian 10 Buster.

Regards,

**Comment by propellerheaddev** [comment]
Still an issue as of October 2019.
