### ISSUE TITLE
Update FruityWifi

### ISSUE THREAD

**Issue by symbios24** [xtr4nge/FruityWifi#237]
Hello, i downloaded both pre-made images for raspberry pi SD image for Raspberry Pi (Pwnpi version) SD image for Raspberry Pi (Raspbian version)

how can i update Fruitywifi on them?

Thanks

**Comment by xtr4nge** [comment]
I will not publish images anymore, and I removed them from the wiki page.
You just need to run the installer. Please use Debian Jessie based systems for the moment.
I will try to update dependencies for Debian Stretch as soon as possible.

regards,
