### ISSUE TITLE
Update Install Wiki

### ISSUE THREAD

**Issue by swoodford** [xtr4nge/FruityWifi#246]
In the GitHub Wiki, [Install page](https://github.com/xtr4nge/FruityWifi/wiki/Install), both [x86/x64 Version](https://github.com/xtr4nge/FruityWifi/wiki/Install#x86x64-version) and [ARM version (Raspberry Pi)](https://github.com/xtr4nge/FruityWifi/wiki/Install#arm-version-raspberry-pi) link to the old install script: [install-FruityWifi.sh](https://github.com/xtr4nge/FruityWifi/blob/master/install-FruityWiFi.sh) which is now a 404.  It should be updated to `install-FruityWifi-{PHPVersion}.sh` or linked out to both PHP version scripts. 😃

**Comment by xtr4nge** [comment]
Hi swoodford, Thanks for reporting this. I updated the wiki. 

Regards,
