### ISSUE TITLE
Is FruityWIFI project alive?

### ISSUE THREAD

**Issue by JopaChlen** [xtr4nge/FruityWifi#247]
Is FruityWIFI project alive?

**Comment by b0bje** [comment]
think I saw a post hinting on a rewrite in rust. (I could be mistaken)

**Comment by xtr4nge** [comment]
Hi guys,
Yes, it is alive. But I have been busy working on other projects.
I added a note on FruityWiFi README, mentioning that for now, I recommend using Debian Jessie based systems, until I can update dependencies and setup for Debian Stretch. 

regards,
