### ISSUE TITLE
what happened to start.sh?

### ISSUE THREAD

**Issue by hwac121** [xtr4nge/FruityWifi#258]
Ok, perhaps I remember incorrectly but didn't this used to have a start.sh and a stop.sh? Got everything installed but um....where do I start this up? I used to be able to easily do this with an included sh file?

**Comment by xtr4nge** [comment]
Hi hwac121, FruityWiFi doesn't have a start/stop script.
All core is PHP, you can install it on anything that supports PHP. The default install script uses Nginx, but you can change it to Apache if you want. You just need to be sure that is mapped correctly.
With the default setup, just be sure that you are installing and starting the correct PHP[5|7] FPM version. 
I never did a proper version for Debian Stretch (but it should work with minor changes).
Soon, I will be preparing a version for Debian Buster.

Regards,
xtr4nge
