### ISSUE TITLE
Offering...

### ISSUE THREAD

**Issue by hwac121** [xtr4nge/FruityWifi#259]
Thanks for the quick response!
After reading your reply it occurred to me it may be one I made my own starting script for. So I looked on my storage drive and found it. I also remembered FruityWiFi works with a Debian or Kali install for Parrot Security (which is what I use) since it is based strongly off the Kali framework.

Anyway, I wanted to share that info with you and my startup script in case you wanted to add it to your application bundle. Thanks again, LOVE this software!
[fruitbowl.sh.tar.gz](https://github.com/xtr4nge/FruityWifi/files/3379263/fruitbowl.sh.tar.gz)

**Comment by xtr4nge** [comment]
Hi hwac121,
Thanks a lot for sharing this ;)
Just for info, I updated the installer to a single installer for systems based on Debian 10 Buster.

Thanks and regards ;)
