### ISSUE TITLE
Which indentation to use?

### ISSUE THREAD

**Issue by Nothing4You** [xtr4nge/FruityWifi#265]
Hi,

I'm trying to improve various files and they're using mixed indentation, sometimes tabs, sometimes spaces. Do you have a preference for this?

**Comment by xtr4nge** [comment]
Hi Nothing4You,
I hope you are well. Thanks for your message.
I would say spaces (4 spaces). 
I am migrating projects to Python (including FruityWiFi core), and I am keeping 4 spaces for indentation.

Regards,
xtr4nge

**Comment by Nothing4You** [comment]
Thanks
