### ISSUE TITLE
Squid 3 upside-down-ternet

### ISSUE THREAD

**Issue by lws803** [xtr4nge/FruityWifi#27]
Hi is it possible to use squid3 module in FruityiWifi to execute commands such as this,  http://www.ex-parrot.com/~pete/upside-down-ternet.html 

its about getting squid's redirection script to work with mogrify.

**Comment by xtr4nge** [comment]
HI lws803
I will release a module very soon.

regards,
xtr4nge

**Comment by xtr4nge** [comment]
Implemented as a plugin for FruityProxy ;)

regards,
