### ISSUE TITLE
Any way to get the client's original intended SSID?

### ISSUE THREAD

**Issue by JackWindows** [xtr4nge/FruityWifi#50]
Is there any way to get the client's probed SSID? I can use karma to phish the clients and make them think I am their desired AP. However, I can't figure out what their original intended SSID. I search on google and found the karma-patched hostapd should generate logs when SSID probe packets are received, but it seems FruityWifi built-in hostapd doesn't generate such log. I think a karma log to display received SSID probes is a good idea.

**Comment by xtr4nge** [comment]
Mana module has been implemented ;)

regards,
xtr4nge
