### ISSUE TITLE
Error Fruitywifi in backbox(ubuntu)

### ISSUE THREAD

**Issue by erik921** [xtr4nge/FruityWifi#58]
Hello,

After downloading the new fruitywifi today there seems to be something wrong with the code.
The login screems seems off showing tags from the code that doesn do anything.
Also there are things like 2 login buttons.

When you press a login button I get this line of code;
. */ ?> "; if ($users[$user] == md5($pass)) { $_SESSION["user_id"] = $user; //echo "welcome"; header('Location: page_status.php'); } else { //echo "get out of here..."; header('Location: index.php?error=1'); } ?>

Is this a problem I caused ?
(I am running the latest version of backbox)

Keep the good work going.
Sincerely,
Erik

**Comment by johnjdoe** [comment]
Perhaps a little bit late, but the problem/solution seems to be the same that mine: https://github.com/xtr4nge/FruityWifi/issues/89

**Comment by xtr4nge** [comment]
Hi johnjdoe,
Thanks for linking these issues/solutions.
i'm closing this issue for now.

xtr4nge
