### ISSUE TITLE
http://localhost:8000 doesn't work

### ISSUE THREAD

**Issue by ntgeralt** [xtr4nge/FruityWifi#59]
sudo sh install-FruityWifi.sh
download a lot,then everything still doesn't work
i am a newble on Linux,and this thing is killng me

**Comment by ms0m** [comment]
I followed this tutorial, tested the open ports with nmap the results are as follows:

PORT     STATE  SERVICE
80/tcp   closed http
443/tcp  open   https
8000/tcp closed http-alt
8443/tcp closed https-alt


Please advise.
