### ISSUE TITLE
Get rid of "danger" in favor of "sudo"

### ISSUE THREAD

**Issue by rhertzog** [xtr4nge/FruityWifi#62]
bin/danger is a really hideous hack allowing any local user to execute anything with root rights. We must get rid of this.

The approach that I suggest is to have all the fruitywifi code run under a dedicated "fruitywifi" user which would have sudo rights to execute commands as root. You could provide a sudoers snippet file that can be copied to /etc/sudoers.d/ to make it just work.

**Comment by harayz** [comment]
i too got the error message below but how to fix it?
 sudo: /etc/sudoers.d/fruitywifi is owned by uid 1000, should be 0

**Comment by lnkakalink** [comment]
harayz 
i am upgrade FruityWifi and start upgrade modules

**Comment by harayz** [comment]
how to do upgrade?
