### ISSUE TITLE
PwnPi image not booting - red LED light only

### ISSUE THREAD

**Issue by PhinPhin** [xtr4nge/FruityWifi#70]
Hi, I try now a few hours to boot up your PwnPi-image, no luck. Every other RasPi-image works, but even the stock PwnPi-one from their website doesn't boot. Any help? They wrote last year already there's a new version that would work with the model B of the RasPi, but my still only shows the red LED.... copying firmwarefiles doesn't work either. :/

**Comment by adrianTNT** [comment]
I have the same problem, would be nice if these docs are updated with 2-3 words, it takes 5 seconds; so we don't waste our time. When we try to install these faulty images, we spend hours, each of us.

**Comment by xtr4nge** [comment]
Hi adrianTNT,
Yes that is a good point. I will update the documentation as soon as possible.

regards,

**Comment by adrianTNT** [comment]
Hi xtr4nge. Thanks.
I know that the rest of the project(s) take a lot of time to develop/maintain, so I do appreciate making these available.

**Comment by xtr4nge** [comment]
No prob ;)

regards,
