### ISSUE TITLE
Autostart missing options

### ISSUE THREAD

**Issue by headii** [xtr4nge/FruityWifi#74]
Hello xtr4nge i like your projekt very much, i just like to let you know there where missing options in the autostart module.

This options are available:

Wireless 
Karma 
Phishing 
ngrep 
SSLStrip 
DNSSpoof 
MDK3 
Squid3 
Kismet 
Captive 
URLSnarf 
Responder 
Tcpdump 
Ettercap 
Autossh

Here  is the list of the available modules:

nmap 1.4
sslstrip 1.7
dnsspoof 1.7
urlsnarf 1.6
mdk3 1.7
ngrep 1.4
captive 1.4
squid3 1.3
kismet 1.2
responder 1.4
autostart 1.2
rpitwit 1.3  <--missing
whatsapp 1.3 <--missing
karma 1.4
nmcli 1.3
3g_4g 1.2 <--missing
supplicant 1.2
meterpreter 1.2
ettercap 1.2  
tcpdump 1.1
autossh 1.1
vfeed 1.1
nessus 1.1  <--missing
tor  1.1   <--missing
phishing 1.1
mana 1.1  <--missing

**Comment by xtr4nge** [comment]
Hi headii,
Thanks a lot, I will take a look ;)

regards,
xtr4nge

**Comment by xtr4nge** [comment]
Module has been updated.

regards,
