### ISSUE TITLE
error Install modules

### ISSUE THREAD

**Issue by lnkakalink** [xtr4nge/FruityWifi#75]
Hi Xtr4nge

Error

pi@IPhone ~/FruityWifi-master $ sudo ./install-modules.py
sudo: /etc/sudoers.d/fruitywifi is owned by uid 1000, should be 0
Traceback (most recent call last):
File "./install-modules.py", line 69, in 
if (float(version)) >= float(info['required']):
ValueError: invalid literal for float(): 2.1.2

regards,
lnkakalink

**Comment by xtr4nge** [comment]
Hi lnkakalink,
Thanks a lot for let me know.
I will update the script as soon as possible.

regards,
xtr4nge

**Comment by xtr4nge** [comment]
install-modules.py script has been updated.

regards,
xtr4nge
