### ISSUE TITLE
Version number issue (2.1.2)

### ISSUE THREAD

**Issue by ShiawasenaHoshi** [xtr4nge/FruityWifi#76]
Hello xtr4nge!
install_modules.py doesn't work because 2.1.2 isn't float type.
If i change version to 2.12 (in config.php) everything works as usually :)

Thank you for FruityWifi :)

**Comment by xtr4nge** [comment]
Hi ShiawasenaHoshi,
Thanks a lot for let me know.
I will update the script as soon as possible.

regards,
xtr4nge

**Comment by xtr4nge** [comment]
install-modules.py script has been updated.

regards,
xtr4nge
