### ISSUE TITLE
Any had a successful ubuntu 14.04 install?

### ISSUE THREAD

**Issue by bytedeez** [xtr4nge/FruityWifi#77]
Tried it but hasn't worked as of yet.

I receive this error when running install-modules.py 
<Traceback (most recent call last):
  File "./install-modules.py", line 69, in <module>
    if (float(version)) >= float(info['required']):
ValueError: invalid literal for float(): 2.1.2>

Was running this script as root. not by being logged in has root. but by doing sudo -i then getting a root shell.

**Comment by headii** [comment]
Hello bytedeez,

i receive the same error as you, when i try to install the modules on debian wheezy.

File "install-modules.py", line 69, in
if (float(version)) >= float(info['required']):
ValueError: invalid literal for float(): 2.1.2

If you change your /usr/share/fruitywifi/www/config/config.php from "2.1.2" to "2.12" then run the "install-modules.py"  it should run normal. 

Have a look @ https://github.com/xtr4nge/FruityWifi/issues/76

You can also install the modules over the webinterface, that should work fine!

**Comment by xtr4nge** [comment]
Hi, thanks a lot for let me know.
I will update the script as soon as possible.

regards,
xtr4nge

**Comment by xtr4nge** [comment]
install-modules.py script has been updated.

regards,
xtr4nge
