### ISSUE TITLE
Unable to connect - after updating modules

### ISSUE THREAD

**Issue by TAz00** [xtr4nge/FruityWifi#79]
I installed FruityWifi on Kali 1.0.9a, and applied the fix to update modules (www/config/config.php -> Version = 2.12)

After running ./install-modules.sh and then rebooting, the server address has moved to https://127.0.1.1:8443/ instead of previous 127.0.0.1

root@kali:~# /etc/init.d/apache2 stop 
[....] Stopping web server: apache2apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1 for ServerName
. ok 

** Edit

Looking further, after running

/etc/init.d/apache2 stop 
/etc/init.d/nginx restart 
/etc/init.d/php5-fpm restart 

on each reboot I can reach the server on both 127.0.1.1 and 127.0.0.1. , but it seems like a bug

**Comment by xtr4nge** [comment]
Hi TAz00,
I will fix the problem with the float numbers as soon as possible. 
Note: the script does not change the IP address.

regards,
xtr4nge

**Comment by xtr4nge** [comment]
install-modules.py script has been updated.

regards,
xtr4nge
