### ISSUE TITLE
Problem with Karma output

### ISSUE THREAD

**Issue by dimitrisre** [xtr4nge/FruityWifi#80]
I have succesfully installed an use Karma.But i cannot see anything on the output area of the module. In fact not only for Karma. If i run Karma from command line i can see all the output.
Can you please help me? 
This is my configuration
![screenshot](https://cloud.githubusercontent.com/assets/7068929/5709247/f0c2585a-9aa0-11e4-95d4-e0fbb3bf3d08.png)

**Comment by xtr4nge** [comment]
Hi dimitrisre,
The log output from Karma it is not implemented in FruityWifi yet (if that is what you are looking for)
Try with [AP] Hostapd-Mana (You need to install Mana module to get this option)

regards,
xtr4nge

**Comment by dimitrisre** [comment]
Ok! Thanks for the answer.

**Comment by xtr4nge** [comment]
No prob. I will publish an update as soon as the Karma logs are implemented.

regards,
xtr4ge
