### ISSUE TITLE
dhcp doenst work

### ISSUE THREAD

**Issue by Asphyriax** [xtr4nge/FruityWifi#84]
I have FruityWifi v2.1.2 installed on my Raspberry pi B+ but the dhcp server doenst work ??

**Comment by xtr4nge** [comment]
Hi Asphyriax,
I need more details about your problem:

- What wireless card are you using? chipset?
- What [AP] mode are you using? (config page)
- Is it the wireless status > `enabled`?

regards,
xtr4nge

**Comment by Asphyriax** [comment]
hello xtr4nge,

first of all: youre awesome,
second im kinda new in this so i will have some more questions.

i wanted to install the img but i dont know what my destination path was so i just installed it in Raspbian.

My wifi card is a ALFA USB WiFi AWUS036NEH
what are the modes;
IN - OUT | AP
IN - -- | AP
IN - OUT
IN - --
-- - OUT

i am formilliar with IP's,Masks, and gateways,

yes wireless is enabled
i was connected with my phone but doesnt reach the internet

i have tried them both but not with all modes

and i had all the modules installed but 3 of them worked

**Comment by xtr4nge** [comment]
Hi Asphyriax
I hope you are well.

Looks like AWUS036NEH it is not supported by Hostapd, please check the following post: https://github.com/xtr4nge/FruityWifi/issues/61

But you still have the Airmon-ng option. Just go to the config page, and set the [AP] mode to `Airmon-ng`

regards,
xtr4nge
