### ISSUE TITLE
Use the master.zip 2.1.2 on pwnpi,can not  start Karma successfully.

### ISSUE THREAD

**Issue by ghosttang** [xtr4nge/FruityWifi#85]
Install was  successful,but can't start Karma.
I've tried this twice.
regards,
ghosttang

**Comment by xtr4nge** [comment]
HI ghosttang,
You need to check the config page, and select [AP] `Hostapd-Karma`, also your wireless card needs to by supported by Hostapd. (for example, Realtek chipsets are not supported)
Same with `Hostapd-Mana`.

regards,
xtr4nge
