### ISSUE TITLE
Autostart Karma (Monitor mode)

### ISSUE THREAD

**Issue by AnguisCaptor** [xtr4nge/FruityWifi#92]
Heey what's up, thanks for your outstanding work :D
I'm having a bit of a problem, I'm running the raspberry pi version 2.1.2

And when ever I put Karma to the Autostart and enable it... it doesn't start karma
I think it's a problem of not having Monitor Mode enabled before karma

Would you be so kind enough to add a option to enable monitor mode at the AutoStart menu
So we can all enjoy Karma at boot :)

**Comment by xtr4nge** [comment]
Hi AnguisCaptor,
I hope you are well. Thanks a lot for letting me know, I will take a look ;)

regards,
xtr4nge

**Comment by AnguisCaptor** [comment]
Cool, I will take a look aswell, I am not a "web dev" myself as I simply don't like it, but I will try to contribute to the project :)

**Comment by xtr4nge** [comment]
Module has been updated.
Thanks AnguisCaptor ;)

regards,
