### ISSUE TITLE
Unable to run wireless

### ISSUE THREAD

**Issue by rooterretoor** [xtr4nge/FruityWifi#97]
Hi,
I have an issue with running wireless. Have got thinkpad t61 and WN722N NIC. My bult-in card does not support AP mode, but Tp-link does. Everything on localhost site is configured, but wireless only works on airmon-ng. I'am unable to use it with karma or mana. System: kali linux.

**Comment by xtr4nge** [comment]
Hi rooterretoor,
The wireless card needs to be supported by Hostapd to use Karma and Mana. 
[AP] Airmon-ng was included in FruityWifi to support more wireless cards, but Karma and Mana are not working with this mode.

regards,
xtr4nge
